name = input("What's your name? \n")
print(" ")
print("Hey "+ name + " !")
print("Welcome! We are going to go through the name of countries starting with any specific letter. Suppose you type the letter 'A' and you will receive the names of all the countries starting with 'A'")

z=input("Enter the alphabet : ")

if z=='A' or z=='a':
    print("1- Afghanistan")
    print("2- Albania")
    print("3- Algeria")
    print("4- American Samoa")
    print("5- Andorra")
    print("6- Angola")
    print("7- Anguilla")
    print("8- Antarctica")
    print("9- Antigua and Barbuda")
    print("10- Argentina")
    print("11- Armenia")
    print("12- Aruba")
    print("13- Austria")
    print("14- Azerbaijan")
elif z=='B' or z=='b':
    print("1- Bahamas")
    print("2- Bahrain")
    print("3- Bangladesh")
    print("4- Barbados")
    print("5- Belarus")
    print("6- Belgium")
    print("7- Belize")
    print("8- Benin")
    print("9- Bermuda")
    print("10- Bhutan")
    print("11- Bolivia")
    print("12- Bosnia and Herzegovina")
    print("13- Botswana")
    print("14- Brazil")
    print("15- Brunei Darussalam")
    print("16- Bulgaria")
    print("17- Burkina Faso")
    print("18- Burundi")
elif z=='c'or z=='C':
    print("1- Cambodia")
    print("2- Cameroon")
    print("3- Canada")
    print("4- Cape Verde")
    print("5- Cayman Islands")
    print("6- Central African Republic")
    print("7- Chad")
    print("8- Chile")
    print("9- China")
    print("10- Christmas Island")
    print("11- Cocos (Keeling) Islands")
    print("12- Colombia")
    print("13- Comoros")
    print("14- Democratic Republic of the Congo (Kinshasa)")
    print("15- Congo, Republic of (Brazzaville)")
    print("16- Costa Rica")
    print("17- Côte D'ivoire (Ivory Coast)")
    print("18- Croatia")
    print("19- Cuba")
    print("20- Cyprus")
    print("21- Czech Republic")
elif z=='D' or z=='d':
    print("1- Denmark")
    print("2- Djibouti")
    print("3- Dominica")
    print("4- Dominican Republic")
elif z=='E' or z=='e':
    print("1- East Timor ")
    print("2- Ecuador")
    print("3- Egypt")
    print("4- El Salvador")
    print("5- Equatorial Guinea")
    print("6- Eritrea")
    print("7- Estonia")
    print("8- Ethiopia")
elif z=='F' or z=='f':
    print("1- Falkland Islands")
    print("2- Faroe Islands")
    print("3- Fiji")
    print("4- Finland")
    print("5- France")
    print("6- French Guiana")
    print("7- French Polynesia")
    print("8- French Southern Territories")
elif z=='G' or z=='g':
    print("1- Gabon")
    print("2- The Gambia")
    print("3- Georgia")
    print("4- Germany")
    print("5- Ghana")
    print("6- Gibraltar")
    print("7- Greece")
    print("8- Greenland")
    print("9- Grenada")
    print("10- Guadeloupe")
    print("11- Guam")
    print("12- Guatemala")
    print("13- Guinea")
    print("14- Guinea-Bissau")
    print("15- Guyana")
elif z=='H' or z=='h':
    print("1- Haiti")
    print("2- Holy See")
    print("3- Honduras")
    print("4- Hong Kong")
    print("5- Hungary")
elif z=='I' or z=='i':
    print("1- Iceland")
    print("2- India")
    print("3- Indonesia")
    print("4- Iran")
    print("5- Iraq")
    print("6- Ireland")
    print("7- Israel")
    print("8- Italy")
    print("9- Ivory Coast")
elif z=='J' or z=='j':
    print("1- Jamaica")
    print("2- Jordan")
    print("3- Japan")
elif z=='K' or z=='k':
    print("1- Kazakhstan")
    print("2- Kenya")
    print("3- Kiribati")
    print("4- Korea, Democratic People's Rep. (North Korea)")
    print("5- Korea, Republic of (South Korea)")
    print("6- Kosovo")
    print("7- Kuwait")
    print("8- Kyrgyzstan")
elif z=='L' or z=='l':
    print("1- Lao, People's Democratic Republic")
    print("2- Latvia")
    print("3- Lebanon")
    print("4- Lesotho")
    print("5- Liberia")
    print("6- Libya")
    print("7- Liechtenstein")
    print("8- Lithuania")
    print("9- Luxembourg")
elif z=='M' or z=='m':
    print("1- Macau")
    print("2- Madagascar")
    print("3- Malawi")
    print("4- Malaysia")
    print("5- Maldives")
    print("6- Mali")
    print("7- Malta")
    print("8- Marshall Islands")
    print("9- Martinique")
    print("10- Mauritania")
    print("11- Mauritius")
    print("12- Mayotte")
    print("13- Mexico")
    print("14- Micronesia")
    print("15- Moldova")
    print("16- Monaco")
    print("17- Mongolia")
    print("18- Montenegro")
    print("19- Montserrat")
    print("20- Morocco")
    print("21- Mozambique")
    print("22- Myanmar, Burma")
elif z=='N' or z=='n':
    print("1- Namibia")
    print("2- Nauru")
    print("3- Nepal")
    print("4- Netherlands")
    print("5- New Caledonia")
    print("6- New Zealand")
    print("7- Nicaragua")
    print("8- Niger")
    print("9- Nigeria")
    print("10- Niue")
    print("11- North Macedonia")
    print("12- Northern Mariana Islands")
    print("13- Norway")
elif z=='O' or z=='o':
    print("1- Oman")
elif z=='P' or z=='p':
    print("1- Pakistan")
    print("2- Palau")
    print("3- Palestinian territories")
    print("4- Panama")
    print("5- Papua New Guinea")
    print("6- Paraguay")
    print("7- Peru")
    print("8- Philippines")
    print("9- Pitcairn Island")
    print("10- Poland")
    print("11- Portugal")
    print("12- Puerto Rico")
elif z=='Q' or z=='q':
    print("1- Qatar")
elif z=='R' or z=='r':
    print("1- Reunion Island")
    print("2- Romania")
    print("3- Russian Federation")
    print("4- Rwanda")
elif z=='S' or z=='s':
    print("1- Saint Kitts and Nevis")
    print("2- Saint Lucia")
    print("3- Saint Vincent and the Grenadines")
    print("4- Samoa")
    print("5- San Marino")
    print("6- Sao Tome and Principe")
    print("7- Saudi Arabia")
    print("8- Senegal")
    print("9- Serbia")
    print("10- Seychelles")
    print("11- Sierra Leone")
    print("12- Singapore")
    print("13- Slovakia (Slovak Republic)")
    print("14- Slovenia")
    print("15- Solomon Islands")
    print("16- Somalia")
    print("17- South Africa")
    print("18- South Sudan")
    print("19- Spain")
    print("20- Sri Lanka")
    print("21- Sudan")
    print("22- Suriname")
    print("23- Swaziland (Eswatini)")
    print("24- Sweden")
    print("25- Switzerland")
    print("26- Syria, Syrian Arab Republic")
elif z=='T' or z=='t':
    print("1- Taiwan")
    print("2- Tajikistan")
    print("3- Tanzania; officially the United Republic of Tanzania")
    print("4- Thailand")
    print("5- Tibet")
    print("6- Togo")
    print("7- Tokelau")
    print("8- Tonga")
    print("9- Trinidad and Tobago")
    print("10- Tunisia")
    print("11- Turkey")
    print("12- Turkmenistan")
    print("13- Turks and Caicos Islands")
    print("14- Tuvalu")
elif z=='U' or z=='u':
    print("1- Uganda")
    print("2- Ukraine")
    print("3- United Arab Emirates")
    print("4- United Kingdom")
    print("5- United States")
    print("6- Uruguay")
    print("7- Uzbekistan")
elif z=='V' or z=='v':
    print("1- Vanuatu")
    print("2- Vatican City State (Holy See)")
    print("3- Venezuela")
    print("4- Vietnam")
    print("5- Virgin Islands (British)")
    print("6- Virgin Islands (U.S.)")
elif z=='W' or z=='w':
    print("1- Wallis and Futuna Islands")
    print("2- Western Sahara")
elif z=='X' or z=='x':
    print("No output to present")
elif z=='Y' or z=='y':
    print("1- Yemen")
elif z=='Z' or z=='z':
    print("1- Zambia")
    print("2- Zimbabwe")
else:
    print("Invalid Input!!! Sahi karo yaar ise...")
    
    
    
